import AboutLanding from '@/components/AboutLanding/AboutLanding';

const About = () => {
  return (
    <div>
      <Head>
        <title>Renewable Resources - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutLanding />
    </div>
  );
};
export default About;
